select
    NULLIF(TRIM(school_name), 'na') as school_name,
    UPPER(TRIM(school_name)) AS school_name_clean,
    NULLIF(TRIM(url_address), 'na') as url_address,
    NULLIF(TRIM(address), 'na') as address,
    postal_code,
    NULLIF(TRIM(telephone_no), 'na') as telephone_no,
    NULLIF(TRIM(telephone_no_2), 'na') as telephone_no_2,
    NULLIF(TRIM(fax_no), 'na') as fax_no,
    NULLIF(TRIM(fax_no_2), 'na') as fax_no_2,
    NULLIF(TRIM(email_address), 'na') as email_address,
    NULLIF(TRIM(mrt_desc), 'na') as mrt_desc,
    NULLIF(TRIM(bus_desc), 'na') as bus_desc,
    NULLIF(TRIM(principal_name), 'na') as principal_name,
    NULLIF(TRIM(first_vp_name), 'na') as first_vp_name,
    NULLIF(TRIM(second_vp_name), 'na') as second_vp_name,
    NULLIF(TRIM(third_vp_name), 'na') as third_vp_name,
    NULLIF(TRIM(fourth_vp_name), 'na') as fourth_vp_name,
    NULLIF(TRIM(fifth_vp_name), 'na') as fifth_vp_name,
    NULLIF(TRIM(sixth_vp_name), 'na') as sixth_vp_name,
    NULLIF(TRIM(dgp_code), 'na') as dgp_code,
    NULLIF(TRIM(zone_code), 'na') as zone_code,
    NULLIF(TRIM(type_code), 'na') as type_code,
    NULLIF(TRIM(nature_code), 'na') as nature_code,
    NULLIF(TRIM(session_code), 'na') as session_code,
    NULLIF(TRIM(mainlevel_code), 'na') as mainlevel_code,
    sap_ind,
    autonomous_ind,
    gifted_ind,
    ip_ind,
    NULLIF(TRIM(mothertongue1_code), 'na') as mothertongue1_code,
    NULLIF(TRIM(mothertongue2_code), 'na') as mothertongue2_code,
    NULLIF(TRIM(mothertongue3_code), 'na') as mothertongue3_code,
    CURRENT_TIMESTAMP() as loaded_at
from  {{ source('sg_moe','raw_schools')}}