select
    NULLIF(school_name, 'na') as school_name,
    UPPER(TRIM(school_name)) AS school_name_clean,
    NULLIF(url_address, 'na') as url_address,
    NULLIF(address, 'na') as address,
    postal_code,
    NULLIF(telephone_no, 'na') as telephone_no,
    NULLIF(telephone_no_2, 'na') as telephone_no_2,
    NULLIF(fax_no, 'na') as fax_no,
    NULLIF(fax_no_2, 'na') as fax_no_2,
    NULLIF(email_address, 'na') as email_address,
    NULLIF(mrt_desc, 'na') as mrt_desc,
    NULLIF(bus_desc, 'na') as bus_desc,
    NULLIF(principal_name, 'na') as principal_name,
    NULLIF(first_vp_name, 'na') as first_vp_name,
    NULLIF(second_vp_name, 'na') as second_vp_name,
    NULLIF(third_vp_name, 'na') as third_vp_name,
    NULLIF(fourth_vp_name, 'na') as fourth_vp_name,
    NULLIF(fifth_vp_name, 'na') as fifth_vp_name,
    NULLIF(sixth_vp_name, 'na') as sixth_vp_name,
    NULLIF(dgp_code, 'na') as dgp_code,
    NULLIF(zone_code, 'na') as zone_code,
    NULLIF(type_code, 'na') as type_code,
    NULLIF(nature_code, 'na') as nature_code,
    NULLIF(session_code, 'na') as session_code,
    NULLIF(mainlevel_code, 'na') as mainlevel_code,
    sap_ind,
    autonomous_ind,
    gifted_ind,
    ip_ind,
    NULLIF(mothertongue1_code, 'na') as mothertongue1_code,
    NULLIF(mothertongue2_code, 'na') as mothertongue2_code,
    NULLIF(mothertongue3_code, 'na') as mothertongue3_code,
    CURRENT_TIMESTAMP() as loaded_at
from  {{ source('sg_moe','raw_schools')}}