select
    school_name,
    url_address,
    address,
    postal_code,
    telephone_no,
    telephone_no_2,
    fax_no,
    fax_no_2,
    email_address,
    mrt_desc,
    bus_desc,
    principal_name,
    first_vp_name,
    second_vp_name,
    third_vp_name,
    fourth_vp_name,
    COALESCE(NULLIF(fifth_vp_name, ''), 'na') as fifth_vp_name,
    COALESCE(NULLIF(sixth_vp_name, ''), 'na') as sixth_vp_name,
    dgp_code,
    zone_code,
    type_code,
    nature_code,
    session_code,
    mainlevel_code,
    sap_ind,
    autonomous_ind,
    gifted_ind,
    ip_ind,
    mothertongue1_code,
    mothertongue2_code,
    mothertongue3_code
from  {{ source('sg_moe','raw_schools')}}