"""
routers/advisor.py

POST /advisor — accepts a natural language question from a parent,
retrieves relevant MOE policy context via BigQuery vector search,
optionally fetches school balloting data via SQL, and returns a
grounded response generated by the configured Groq advisor model sequence.

No is_active or phase filter applied here — the advisor surfaces
context for any valid question including inactive schools.
"""

from fastapi import APIRouter, HTTPException
from api.config import settings
from api.models.advisor import AdvisorRequest, AdvisorResponse, SourceDocument
from api.services.advisor import run_advisor

router = APIRouter(prefix="/advisor", tags=["Advisor"])


@router.post("", response_model=AdvisorResponse, response_model_exclude_none=True)
async def ask_advisor(request: AdvisorRequest):
    try:
        result = run_advisor(
            question=request.question,
            school_names=request.school_names,
            conversation_history=request.conversation_history,
        )
    except Exception as e:
        # Temporary: print real error for debugging
        # import traceback
        # traceback.print_exc()
        
        # Surface as 503 rather than 500 — likely a Groq or Vertex AI
        # transient failure, not a code bug
        raise HTTPException(
            status_code=503,
            detail=(
                "The advisor is temporarily unavailable. "
                "Please try again in a moment."
            ),
        ) from e

    return AdvisorResponse(
        answer=result["answer"],
        sources=[SourceDocument(**s) for s in result["sources"]],
        school_context_used=result["school_context_used"],
        disclaimer=result["disclaimer"],
        # debug_best_distance=result["_debug_best_distance"],
        # debug_school_names=result["_debug_school_names"],
        model_used=(
            result.get("model_used")
            if settings.advisor_show_model_used
            else None
        ),
    )